# Evaluacion intermedia

In [21]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None) 
# Para ver los datos Float en formato con decimales y nos quita la notacion cientifica
# pd.set_option('display.float_format', '{:.2f}'.format)

In [22]:
df = pd.read_csv("Spotify_Youtube.csv", index_col=0)

## Exploraci√≥n del conjunto de datos:

In [23]:
df.head()

,Artist,Url_spotify,Track,Album,Album_type,Uri,Danceability,Energy,Key,Loudness,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Duration_ms,Url_youtube,Title,Channel,Views,Likes,Comments,Description,Licensed,Official_video,Stream
0,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Feel Good Inc.,Demon Days,album,spotify:track:0d28khcov6AiegSCpG5TuT,"0,818","0,705","6,0","-6,679","0,177","0,00836","0,00233",0.6130,0.772,138.559,222640.0,https://www.youtube.com/watch?v=HyHNuVaZJ-k,Gorillaz - Feel Good Inc. (Official Video),Gorillaz,693555221.0,6220896.0,169907.0,Official HD Video for Gorillaz' fantastic trac...,True,True,1.040235e+09
1,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Rhinestone Eyes,Plastic Beach,album,spotify:track:1foMv2HQwfQ2vntFf9HFeG,"0,676","0,703","8,0","-5,815","0,0302","0,0869","0,000687",0.0463,0.852,92.761,200173.0,https://www.youtube.com/watch?v=yYDmaexVHic,Gorillaz - Rhinestone Eyes [Storyboard Film] (...,Gorillaz,72011645.0,1079128.0,31003.0,The official video for Gorillaz - Rhinestone E...,True,True,3.100837e+08
2,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,New Gold (feat. Tame Impala and Bootie Brown),New Gold (feat. Tame Impala and Bootie Brown),single,spotify:track:64dLd6rVqDLtkXFYrEUHIU,"0,695","0,923","1,0","-3,93","0,0522","0,0425","0,0469",0.1160,0.551,108.014,215150.0,https://www.youtube.com/watch?v=qJa-VFwPpYA,Gorillaz - New Gold ft. Tame Impala & Bootie B...,Gorillaz,8435055.0,282142.0,7399.0,Gorillaz - New Gold ft. Tame Impala & Bootie B...,True,True,6.306347e+07
3,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,On Melancholy Hill,Plastic Beach,album,spotify:track:0q6LuUqGLUiCPP1cbdwFs3,"0,689","0,739","2,0","-5,81","0,026","1,51e-05","0,509",0.0640,0.578,120.423,233867.0,https://www.youtube.com/watch?v=04mfKJWDSzI,Gorillaz - On Melancholy Hill (Official Video),Gorillaz,211754952.0,1788577.0,55229.0,Follow Gorillaz online:\nhttp://gorillaz.com \...,True,True,4.346636e+08
4,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Clint Eastwood,Gorillaz,album,spotify:track:7yMiX7n9SBvadzox8T5jzT,"0,663","0,694","10,0","-8,627","0,171","0,0253","0,0",0.0698,0.525,167.953,340920.0,https://www.youtube.com/watch?v=1V_xRb0x9aw,Gorillaz - Clint Eastwood (Official Video),Gorillaz,618480958.0,6197318.0,155930.0,The official music video for Gorillaz - Clint ...,True,True,6.172597e+08

In [24]:
df.tail()

,Artist,Url_spotify,Track,Album,Album_type,Uri,Danceability,Energy,Key,Loudness,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Duration_ms,Url_youtube,Title,Channel,Views,Likes,Comments,Description,Licensed,Official_video,Stream
20713,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,JUST DANCE HARDSTYLE,JUST DANCE HARDSTYLE,single,spotify:track:0RtcKQGyI4hr8FgFH1TuYG,"0,582","0,926","5,0","-6,344","0,0328","0,448","0,0",0.0839,0.6580,90.002,94667.0,https://www.youtube.com/watch?v=5SHmKFKlNqI,JUST DANCE HARDSTYLE,SICK LEGEND - Topic,71678.0,1113.0,0.0,Provided to YouTube by Routenote\n\nJUST DANCE...,True,True,9227144.0
20714,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,SET FIRE TO THE RAIN HARDSTYLE,SET FIRE TO THE RAIN HARDSTYLE,single,spotify:track:3rHvPA8lUnPBkaLyPOc0VV,"0,531","0,936","4,0","-1,786","0,137","0,028","0,0",0.0923,0.6570,174.869,150857.0,https://www.youtube.com/watch?v=ocTH6KxllDQ,SET FIRE TO THE RAIN HARDSTYLE,SICK LEGEND - Topic,164741.0,2019.0,0.0,Provided to YouTube by Routenote\n\nSET FIRE T...,True,True,10898176.0
20715,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,OUTSIDE HARDSTYLE SPED UP,OUTSIDE HARDSTYLE SPED UP,single,spotify:track:4jk00YxPtPbhvHJE9N4ddv,"0,443","0,83","4,0","-4,679","0,0647","0,0243","0,0",0.1540,0.4190,168.388,136842.0,https://www.youtube.com/watch?v=5wFhE-HY0hg,OUTSIDE HARDSTYLE SPED UP,SICK LEGEND - Topic,35646.0,329.0,0.0,Provided to YouTube by Routenote\n\nOUTSIDE HA...,True,True,6226110.0
20716,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,ONLY GIRL HARDSTYLE,ONLY GIRL HARDSTYLE,single,spotify:track:5EyErbpsugWliX006eTDex,"0,417","0,767","9,0","-4,004","0,419","0,356","0,0184",0.1080,0.5390,155.378,108387.0,https://www.youtube.com/watch?v=VMFLbFRNCn0,ONLY GIRL HARDSTYLE,SICK LEGEND - Topic,6533.0,88.0,0.0,Provided to YouTube by Routenote\n\nONLY GIRL ...,True,True,6873961.0
20717,SICK LEGEND,https://open.spotify.com/artist/3EYY5FwDkHEYLw...,MISS YOU HARDSTYLE,MISS YOU HARDSTYLE,single,spotify:track:6lOn0jz1QpjcWeXo1oMm0k,"0,498","0,938","6,0","-4,543","0,107","0,00277","0,911",0.1360,0.0787,160.067,181500.0,https://www.youtube.com/watch?v=zau0dckCFi0,MISS YOU HARDSTYLE,SICK LEGEND - Topic,158697.0,2484.0,0.0,Provided to YouTube by Routenote\n\nMISS YOU H...,True,True,5695584.0

In [25]:
df.sample(10)

,Artist,Url_spotify,Track,Album,Album_type,Uri,Danceability,Energy,Key,Loudness,Speechiness,Acousticness,Instrumentalness,Liveness,Valence,Tempo,Duration_ms,Url_youtube,Title,Channel,Views,Likes,Comments,Description,Licensed,Official_video,Stream
7638,Killswitch Engage,https://open.spotify.com/artist/37394IP6uhnjIp...,Holy Diver,As Daylight Dies (Special Edition),album,spotify:track:3a9urnht8HvfFzPwd0ipx6,"0,369","0,995","0,0","-2,584","0,12","7,6e-05","0,00589",0.2410,0.270,185.985,250253.0,https://www.youtube.com/watch?v=NR7dG_m3MsI,Killswitch Engage - Holy Diver [OFFICIAL VIDEO],Roadrunner Records,42600278.0,231933.0,19164.0,Killswitch Engage's music video for 'Holy Dive...,True,True,103153963.0
15965,Travis Scott,https://open.spotify.com/artist/0Y5tJX1MQlPlqi...,Fair Trade (with Travis Scott),Certified Lover Boy,album,spotify:track:40iJIUlhi6renaREYGeIDS,"0,666","0,465","1,0","-8,545","0,26","0,0503","0,0",0.2150,0.292,167.937,291175.0,https://www.youtube.com/watch?v=_ZDLaRzwGiQ,"Drake ""Fair Trade"" ft. Travis Scott (Music Video)",Rap Radio,3310938.0,22143.0,291.0,Special Offer For New Artists üî•üî•üî•\nsubmit your...,False,False,470567628.0
2728,Jos√© Feliciano,https://open.spotify.com/artist/7K78lVZ8XzkjfR...,Un Veneno - G-Mix,El Madrile√±o,album,spotify:track:4wNxcizGKSTfKm1emmO4yk,"0,521","0,45","2,0","-7,339","0,0913","0,773","0,000348",0.1150,0.580,81.376,193693.0,https://www.youtube.com/watch?v=O47dd6lmpxs,"C. Tangana, Jos√© Feliciano, Ni√±o de Elche - Un...",CTanganaVEVO,4071943.0,60880.0,935.0,C. Tangana con Jos√© Feliciano y Ni√±o de Elche ...,True,True,21011624.0
5984,Ilaiyaraaja,https://open.spotify.com/artist/3m49WVMU4zCkaV...,"Unna Nenachu (From ""Psycho (Tamil)"")","Unna Nenachu [From ""Psycho (Tamil)""]",single,spotify:track:5KW8kOHmXqkDEdj6JyP3dJ,"0,331","0,235","4,0","-13,816","0,0411","0,891","2,98e-06",0.1070,0.252,82.511,275504.0,https://www.youtube.com/watch?v=jFWsj_QT0G8,Psycho - Unna Nenachu Video | Udhayanidhi Stal...,SonyMusicSouthVEVO,77179288.0,623813.0,21091.0,Presenting the inimitable Maestro #Ilaiyaraaja...,True,True,17060305.0
18202,Bryant Myers,https://open.spotify.com/artist/6w9ToX5slZ4uId...,Como Panas,Bendecido,album,spotify:track:54tOFoIdt8qXgIzlPpXtVF,"0,638","0,609","10,0","-5,929","0,214","0,407","0,0",0.1460,0.377,157.947,198997.0,https://www.youtube.com/watch?v=0gvKguoXuOo,Como Panas - Bryant Myers (Video oficial),MUSIC LYRICS,746085.0,10170.0,72.0,c√≥mo panas Bryant Myers (video oficial) / crea...,False,False,64837989.0
15343,blackbear,https://open.spotify.com/artist/2cFrymmkijnjDg...,do re mi,digital druglord,album,spotify:track:6Se3x9ANMLv0dCDsjGmEjh,"0,745","0,593","8,0","-6,35","0,0524","0,00522","5,06e-06",0.1230,0.170,111.001,212027.0,https://www.youtube.com/watch?v=dfzlUHOFQ5k,blackbear - do re mi ft. Gucci Mane (Official ...,blackbearVEVO,204429389.0,2299535.0,57248.0,blackbear ‚Äì do re mi feat ‚Äì Gucci Mane\nfull l...,True,True,558809408.0
10835,Kany Garc√≠a,https://open.spotify.com/artist/69UypehHabb68u...,Hoy Ya Me Voy,Cualquier D√≠a,album,spotify:track:58zE9NyMKGTpzV5J8WyXXe,"0,622","0,508","7,0","-7,17","0,03","0,739","1,48e-06",0.1110,0.370,140.038,235813.0,https://www.youtube.com/watch?v=8bAfqhjQTb4,Kany Garc√≠a - Hoy Ya Me Voy (Video),kanygarciaVEVO,189939069.0,534281.0,11947.0,V√≠deo oficial de Kany Garcia de su tema 'Hoy Y...,True,True,50202696.0
5240,D12,https://open.spotify.com/artist/5Qi4Bb7a8C0a00...,40 Oz.,D-12 World,album,spotify:track:3SNIM6IPegio1UqXCYAhoc,"0,73","0,798","1,0","-4,105","0,209","0,0785","0,0",0.3390,0.448,82.986,242520.0,https://www.youtube.com/watch?v=1m49X1OZajw,D12 - 40 Oz. (Official Video - Dirty Version),EminemExplicit,165471.0,3595.0,176.0,40 Oz. by D12\n¬© 2004 Shady/Interscope Records.,False,False,11250707.0
2694,Andr√©s Calamaro,https://open.spotify.com/artist/3tAICgiSR5PfYY...,Hong Kong,El Madrile√±o,album,spotify:track:4kD4ZzJ1rZIVfJ9qw85CVT,"0,649","0,376","4,0","-7,528","0,039","0,0626","2,72e-05",0.0911,0.434,97.848,203507.0,https://www.youtube.com/watch?v=XLLkSBLqlvQ,"C. Tangana, Andr√©s Calamaro - Hong Kong (Video...",CTanganaVEVO,8464880.0,128106.0,3727.0,C. Tangana con Andr√©s Calamaro ‚Äì Hong Kong\n...,True,True,26421597.0
16259,AURORA,https://open.spotify.com/artist/1WgXqy2Dd70QQO...,Into the Unknown,Frozen 2 (Original Motion Picture Soundtrack/D...,compilation,spotify:track:3Z0oQ8r78OUaHvGPiDBR3W,"0,323","0,405","10,0","-8,533","0,0413","0,849","0,000544",0.1380,0.274,145.104,194848.0,https://www.youtube.com/watch?v=54YAA7e2kt8,AURORA - Into the Unknown (Concept Music Video),y2k_moon,948827.0,44045.0,920.0,I've made this video because I've being obsess...,False,False,321316598.0

In [26]:
df.shape

(20718, 27)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20718 entries, 0 to 20717
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Artist            20718 non-null  object
 1   Url_spotify       20718 non-null  object
 2   Track             20718 non-null  object
 3   Album             20718 non-null  object
 4   Album_type        20718 non-null  object
 5   Uri               20718 non-null  object
 6   Danceability      20716 non-null  object
 7   Energy            20716 non-null  object
 8   Key               20716 non-null  object
 9   Loudness          20716 non-null  object
 10  Speechiness       20716 non-null  object
 11  Acousticness      20716 non-null  object
 12  Instrumentalness  20716 non-null  object
 13  Liveness          20716 non-null  float64
 14  Valence           20716 non-null  float64
 15  Tempo             20716 non-null  float64
 16  Duration_ms       20716 non-null  float64
 17  Url_youtube       20248 non-null  object
 18  Title             20248 non-null  object
 19  Channel           20248 non-null  object
 20  Views             20248 non-null  float64
 21  Likes             20177 non-null  float64
 22  Comments          20149 non-null  float64
 23  Description       19842 non-null  object
 24  Licensed          20248 non-null  object
 25  Official_video    20248 non-null  object
 26  Stream            20142 non-null  float64
dtypes: float64(8), object(19)
memory usage: 4.4+ MB

In [202]:
round(df.isnull().sum()/df.shape[0]*100,2)

artist              0.00
url_spotify         0.00
track               0.00
album               0.00
album_type          0.00
uri                 0.00
danceability        0.01
energy              0.01
key                 0.01
loudness            0.01
speechiness         0.01
acousticness        0.01
instrumentalness    0.01
liveness            0.01
valence             0.01
tempo               0.01
duration_ms         0.01
url_youtube         2.27
title               2.27
channel             2.27
views               2.27
likes               2.61
comments            2.75
description         4.23
licensed            2.27
official_video      2.27
stream              2.78
dtype: float64

In [29]:
df.duplicated().sum()

0

In [30]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Liveness,20716.0,1.935210e-01,1.685309e-01,0.0145,9.410000e-02,1.250000e-01,2.370000e-01,1.000000e+00
Valence,20716.0,5.298533e-01,2.454408e-01,0.0000,3.390000e-01,5.370000e-01,7.262500e-01,9.930000e-01
Tempo,20716.0,1.206383e+02,2.957902e+01,0.0000,9.700200e+01,1.199650e+02,1.399350e+02,2.433720e+02
Duration_ms,20716.0,2.247176e+05,1.247905e+05,30985.0000,1.800095e+05,2.132845e+05,2.524430e+05,4.676058e+06
Views,20248.0,9.393782e+07,2.746443e+08,0.0000,1.826002e+06,1.450110e+07,7.039975e+07,8.079649e+09
Likes,20177.0,6.633411e+05,1.789324e+06,0.0000,2.158100e+04,1.244810e+05,5.221480e+05,5.078865e+07
Comments,20149.0,2.751899e+04,1.932347e+05,0.0000,5.090000e+02,3.277000e+03,1.436000e+04,1.608314e+07
Stream,20142.0,1.359422e+08,2.441321e+08,6574.0000,1.767486e+07,4.968298e+07,1.383581e+08,3.386520e+09

In [31]:
df.describe(include = "object").T

,count,unique,top,freq
Artist,20718,2079,Gorillaz,10
Url_spotify,20718,2079,https://open.spotify.com/artist/3AA28KZvwAUcZu...,10
Track,20718,17841,El Ultimo Adi√≥s - Varios Artistas Version,24
Album,20718,11937,Greatest Hits,30
Album_type,20718,3,album,14926
Uri,20718,18862,spotify:track:0tzixmHNQfE6S6SirSToxW,24
Danceability,20716,898,"0,687",78
Energy,20716,1268,"0,572",60
Key,20716,12,"0,0",2305
Loudness,20716,9417,"-7,818",25
Speechiness,20716,1303,"0,0324",72
Acousticness,20716,3138,"0,114",50
Instrumentalness,20716,4012,"0,0",9391
Url_youtube,20248,18154,https://www.youtube.com/watch?v=GqOvxbFLwjY,18
Title,20248,18146,Color Esperanza 2020 - Various Artists (Offici...,18
Channel,20248,6714,T-Series,238
Description,19842,17395,,114
Licensed,20248,2,True,14140
Official_video,20248,2,True,15723

## Preparaci√≥n de los datos:

- Los nombres de las columnas empiezan con may√∫sculas, pon todos los nombres de las columnas en min√∫sculas.

In [32]:
df.columns

Index(['Artist', 'Url_spotify', 'Track', 'Album', 'Album_type', 'Uri',
       'Danceability', 'Energy', 'Key', 'Loudness', 'Speechiness',
       'Acousticness', 'Instrumentalness', 'Liveness', 'Valence', 'Tempo',
       'Duration_ms', 'Url_youtube', 'Title', 'Channel', 'Views', 'Likes',
       'Comments', 'Description', 'Licensed', 'Official_video', 'Stream'],
      dtype='object')

In [203]:
nombres_columnas = {columna : columna.lower() for columna in df.columns}
df.rename(columns=nombres_columnas, inplace=True)
df.columns

Index(['artist', 'url_spotify', 'track', 'album', 'album_type', 'uri',
       'danceability', 'energy', 'key', 'loudness', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'duration_ms', 'url_youtube', 'title', 'channel', 'views', 'likes',
       'comments', 'description', 'licensed', 'official_video', 'stream'],
      dtype='object')

- Haciendo el an√°lisis exploratorio te deber√≠as haber dado cuenta de que algunas de las variables (`danceability`, `energy`, `key`, `loudness`, `speechiness`, `acousticness`, `instrumentalness`) no son del tipo que deber√≠an. Esto es debido a que los decimales est√°n establecidos como comas y no con puntos. Crea una funci√≥n que nos permita cambiar esas comas por puntos para que los datos tengan el tipo correcto. 

- Despu√©s de haber hecho los cambios, chequea los tipos de datos. ¬øSon ya del tipo correcto? En caso de que no, crea otra funci√≥n o modifica la anterior para que sean de tipo *float*.

In [37]:
def cambio_signos_puntuacion(elemento):

    try:     
        return float(elemento.replace(",","."))
    
    except:
        return np.nan

In [38]:
columnas_cambios = ["danceability", "energy", "key", "loudness", "speechiness", "acousticness", "instrumentalness"]

In [39]:
for columna in columnas_cambios:
    df[columna] = df[columna].apply(cambio_signos_puntuacion)

In [46]:
for columna in columnas_cambios:
    print(f"la columnas {columna.upper()} es de tipo:{df[columna].dtype}")

# Podemos hacer df.dtypes y ahorrarnos el bucle

la columnas DANCEABILITY es de tipo:float64
la columnas ENERGY es de tipo:float64
la columnas KEY es de tipo:float64
la columnas LOUDNESS es de tipo:float64
la columnas SPEECHINESS es de tipo:float64
la columnas ACOUSTICNESS es de tipo:float64
la columnas INSTRUMENTALNESS es de tipo:float64

- Hay algunas canciones cuyo t√≠tulo est√° en may√∫sulas. Crea una funci√≥n para que todos los t√≠tulos est√©n en min√∫scula. Haz lo mismo para las columnas de "title" y "album".

In [49]:
columnas_cambios_miniscula =["track", "title", "album"]

In [50]:
for columna in columnas_cambios_miniscula:
    df[columna] = df[columna].str.lower()

Lo podemos hacer sobre el DF como se puede ver arriba o haciendo una funcion y aplicando a cada celda con apply

In [53]:
def cambio_minusculas(celda):
    try:
        return celda.lower()
    except:
        return None

In [ ]:
for columna in columnas_cambios_miniscula:
    df[columna] = df[columna].apply(cambio_minusculas)

In [ ]:
# Para hacerlo con una lambda
for col in columnas_cambios_miniscula:
    df[col] = df[col].apply(lambda dato: dato.lower() if type(dato)== str else dato)

- Algunos de los artistas tienen s√≠mbolos raros, en concreto el s√≠mbolo `$`. Crea una funci√≥n que los reemplaze pos "s".

In [206]:
# hacer la comprobacion
# Sin regex
df[df["artist"].str.contains("$", regex = False)]["artist"].unique()

# Con regex
df[df["artist"].str.contains("\$", regex = True)]["artist"].unique()

In [63]:
columnas_cambios_simbolo = ["artist"]

In [64]:
def cambio_simbolo(celda):
    return celda.replace("$","s")

In [65]:
for columna in columnas_cambios_simbolo:
    df[columna] = df[columna].apply(cambio_simbolo)

In [208]:
# Lo podemos hacer con una lambda
df["artist"] = df["artist"].apply(lambda dato: dato.replace("$","S"))

# Comprobamos que nos ha cambiado los datos, nuestro objetivo es que la lista que devuelva este vacia
df[df["artist"].str.contains("$", regex = False)]["artist"].unique()

array([], dtype=object)

## Filtrado de datos:

- ¬øCu√°les son los valores √∫nicos de la columna "album_type"? Crea tres *dataframes* diferentes, uno para cada tipo de "album_type". ¬øCu√°ntas canciones tenemos en cada tipo?

In [69]:
df["album_type"].unique()

array(['album', 'single', 'compilation'], dtype=object)

In [71]:
df.groupby("album_type")["album_type"].count().reset_index(name="Recuento")

#Esto lo podemos hacer con un value counts de maneramas sencilla
#df["album_type"].value_counts()

    album_type  Recuento
0        album     14926
1  compilation       788
2       single      5004

In [220]:
# Creacion de 3 DF por tipo de album

df_single = df[df["album_type"] == "single"]
df_comp = df[df["album_type"] == "compilation"]
df_album = df[df["album_type"] == "album"]

- Usando el *dataframe* de los albumes que hemos creado en el ejercicio anterior. ¬øCu√°l es la media y la desviaci√≥n est√°ndar de "danceability", "acousticness" y "speechiness" de cada artista?. Muesrtra los resultados en tres dataframes diferentes, uno para cada m√©trica ("danceability", "acousticness" y "speechiness"). Ordena los resultados de mayor a menor en base a la media.

- **BONUS** Haced lo mismo para los datos de tipo "single".

In [227]:
metrica = ["danceability", "acousticness","speechiness"]
categorias = {"album" : df_album, "single": df_single}

In [229]:
for n, d in categorias.items():
    for i in metrica:
        print(f"Dataframe {n}, metrica {i}")
        display(d.groupby("artist")[i].agg(["mean","std"]).reset_index().sort_values(by= "mean", ascending= False))
        print("________________" )

Dataframe album, metrica danceability

                      artist      mean       std
1003                   Latto  0.922333  0.014503
1261                   Murda  0.911500  0.030406
848                    Jon Z  0.886000  0.015556
204                 Blueface  0.885000  0.043782
887                Jung Kook  0.881000       NaN
...                      ...       ...       ...
1661        Stephen Cleobury  0.142067  0.042212
1341            Ocean Sounds  0.137980  0.063706
1342   Ocean Waves For Sleep  0.133533  0.061768
1897  White Noise for Babies  0.090262  0.163895
1896  White Noise Baby Sleep  0.066270  0.071434

[1989 rows x 3 columns]

________________
Dataframe album, metrica acousticness

                   artist      mean       std
351        Claude Debussy  0.993714  0.001380
1509      Robert Schumann  0.993444  0.004902
601        Franz Schubert  0.989500  0.005237
506          Edvard Grieg  0.989500  0.007863
607       Fr√©d√©ric Chopin  0.989286  0.004071
...                   ...       ...       ...
1879              Volbeat  0.000220  0.000237
1254  Motionless In White  0.000166  0.000191
947     Killswitch Engage  0.000132  0.000158
963              Kordhell  0.000083       NaN
747             In Flames  0.000070  0.000128

[1989 rows x 3 columns]

________________
Dataframe album, metrica speechiness

                      artist      mean       std
1626  Sir Arthur Conan Doyle  0.952300  0.008845
181          Bibi Blocksberg  0.945300  0.011879
1601         Sherlock Holmes  0.939300  0.015833
1698                    TKKG  0.919300  0.023542
613             F√ºnf Freunde  0.906200  0.048960
...                      ...       ...       ...
1877           Vishal Mishra  0.027400       NaN
1476            Randy Travis  0.027071  0.004159
347     Cigarettes After Sex  0.027057  0.001265
1478            Rashmi Virag  0.025300       NaN
1544                    SYML  0.025300       NaN

[1989 rows x 3 columns]

________________
Dataframe single, metrica danceability

                      artist    mean       std
1192                The Game  0.9340       NaN
357                  El Alfa  0.9250       NaN
963                Peter Fox  0.9110  0.011314
869                   N.W.A.  0.9050       NaN
636                    Kelis  0.9030       NaN
...                      ...     ...       ...
413           Franz Schubert  0.1630       NaN
290              Daniel Hope  0.0979       NaN
920    Ocean Waves For Sleep  0.0797       NaN
1120        Sir Simon Rattle  0.0640       NaN
1283  White Noise for Babies  0.0000       NaN

[1355 rows x 3 columns]

________________
Dataframe single, metrica acousticness

                   artist      mean       std
577       Johannes Brahms  0.995000       NaN
412           Franz Liszt  0.993000       NaN
1305               Yiruma  0.993000  0.001414
246        Claude Debussy  0.992500  0.000707
194   Camille Saint-Sa√´ns  0.992000       NaN
...                   ...       ...       ...
517             In Flames  0.000021  0.000018
830             Metallica  0.000018  0.000009
452                Gojira  0.000017       NaN
1308              Youjeen  0.000010       NaN
298              Daughtry  0.000007       NaN

[1355 rows x 3 columns]

________________
Dataframe single, metrica speechiness

                      artist    mean       std
268                   D.O.E.  0.7010       NaN
148                 Blueface  0.5885  0.419314
266           D-Block Europe  0.5280       NaN
1181           Tego Calder√≥n  0.5160       NaN
270                   DIVINE  0.4510       NaN
...                      ...     ...       ...
1253                      U2  0.0248       NaN
69            Andrea Bocelli  0.0247       NaN
861              Mr.Children  0.0245       NaN
1117            Simple Minds  0.0243       NaN
1283  White Noise for Babies  0.0000       NaN

[1355 rows x 3 columns]

________________

- Se quiere estudiar si existe una relaci√≥n entre la cantidad de visitas que reciben los videos de m√∫sica de un artista en una plataforma de streaming y la cantidad de likes que estos videos obtienen. Por lo tanto, querremos contestar a la siguiente pregunta: ¬øSon aquellos artistas que tienen m√°s visitas los que m√°s likes tienen? Para solucionar este ejercicio deber√©is: 

        - Agrupa por artista y calcular la media de visitas y de likes.

        - Quedate con los 10 artistas que m√°s visitas han tenido.

        - Quedate con los 10 artistas que m√°s likes han tenido.

In [236]:
artista_like = df.groupby("artist")[["views","likes"]].mean()

#Tambien lo podemos hacer:
# artista_like = df.groupby("artist").agg({"views":"mean", 'likes':'mean'}).reset_index()

artista_like

                         views      likes
artist
(G)I-DLE           175495394.1  2446296.3
*NSYNC             102783286.2   423342.3
070 Shake            9609935.9   201300.5
112                 21913445.9   150914.1
11:11 Music Group    1267282.4    17970.1
...                        ...        ...
will.i.am          283132016.6  1386447.1
√Ångela Aguilar     138529529.1  1029475.7
√ëejo                62668082.4   434891.0
√ëengo Flow          81272631.5   676034.0
√òneheart             3462331.0   127216.7

[2079 rows x 2 columns]

In [235]:
artista_10views = df.groupby("artist").agg({"views":"mean", 'likes':'mean'}).reset_index().sort_values(by= "views", ascending= False)
artista_10views.head(10)

                       artist         views      likes
524                Ed Sheeran  1.546021e+09  8354331.9
372                 CoComelon  1.460167e+09  4171391.3
953                Katy Perry  1.312063e+09  6306709.0
331              Charlie Puth  1.216759e+09  8633692.5
1147               Luis Fonsi  1.162811e+09  6690848.9
925             Justin Bieber  1.099106e+09  7858434.8
420              Daddy Yankee  1.087193e+09  6551817.1
265                Bruno Mars  1.024092e+09  5961614.6
1182  Macklemore & Ryan Lewis  1.012206e+09  6604141.0
379                  Coldplay  9.997278e+08  6315789.5

In [135]:
artista_10_likes = df.groupby("artist").agg({"views":"mean", 'likes':'mean'}).reset_index().sort_values(by= "likes", ascending= False)
artista_10_likes.head(10)

               artist         views       likes
151               BTS  5.607867e+08  13940380.8
149         BLACKPINK  9.392962e+08  13230250.5
331      Charlie Puth  1.216759e+09   8633692.5
524        Ed Sheeran  1.546021e+09   8354331.9
925     Justin Bieber  1.099106e+09   7858434.8
200     Billie Eilish  4.821569e+08   7333853.7
775   Imagine Dragons  9.093785e+08   7227447.7
55        Alan Walker  7.256847e+08   6797770.2
416          DJ Snake  9.180268e+08   6777583.1
1147       Luis Fonsi  1.162811e+09   6690848.9

In [200]:
datos_single = df[df["album_type"] == "single"].groupby("album_type").agg({'views': 'count', 'likes': 'count'}).reset_index()

datos_single

  album_type  views  likes
0     single   4860   4852

In [ ]:
datos_single= df.groupby("artist").agg({"views":"mean", 'likes':'mean'}).reset_index()

- Ahora queremos analizar la colaboraci√≥n entre artistas en la industria musical, se tienen datos de las colaboraciones realizadas en los √∫ltimos a√±os. Se desea conocer cu√°les son los artistas que han colaborado en mayor cantidad de canciones y generar un *ranking* con los diez primeros. ¬øQu√© artistas con los que m√°s colaboraciones tienen? Para esto tendr√©is que:

        - Filtra los datos para quedarte solo con aquellos datos donde en la columna "track" tengamos "feat".

        - Cuenta cuantas canciones tiene cada artista utilizando el *dataframe* generado en el paso anterior.
    

        - Debes contestar a las siguientes preguntas:

            - ¬øCu√°les son los diez artistas que m√°s han colaborado  seg√∫n los datos que tenemos?

            - ¬øCu√°l es el n√∫mero de canciones en los que ha colaborado el artista que ocupa el primer lugar en el *ranking*?

            - ¬øCu√°l es el artista que ocupa el d√©cimo lugar en el *ranking* y en cu√°ntas canciones ha colaborado?

In [137]:
df.head()

,artist,url_spotify,track,album,album_type,uri,danceability,energy,key,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,url_youtube,title,channel,views,likes,comments,description,licensed,official_video,stream
0,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,feel good inc.,demon days,album,spotify:track:0d28khcov6AiegSCpG5TuT,0.818,0.705,6.0,-6.679,0.1770,0.008360,0.002330,0.6130,0.772,138.559,222640.0,https://www.youtube.com/watch?v=HyHNuVaZJ-k,gorillaz - feel good inc. (official video),Gorillaz,693555221.0,6220896.0,169907.0,Official HD Video for Gorillaz' fantastic trac...,True,True,1.040235e+09
1,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,rhinestone eyes,plastic beach,album,spotify:track:1foMv2HQwfQ2vntFf9HFeG,0.676,0.703,8.0,-5.815,0.0302,0.086900,0.000687,0.0463,0.852,92.761,200173.0,https://www.youtube.com/watch?v=yYDmaexVHic,gorillaz - rhinestone eyes [storyboard film] (...,Gorillaz,72011645.0,1079128.0,31003.0,The official video for Gorillaz - Rhinestone E...,True,True,3.100837e+08
2,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,new gold (feat. tame impala and bootie brown),new gold (feat. tame impala and bootie brown),single,spotify:track:64dLd6rVqDLtkXFYrEUHIU,0.695,0.923,1.0,-3.930,0.0522,0.042500,0.046900,0.1160,0.551,108.014,215150.0,https://www.youtube.com/watch?v=qJa-VFwPpYA,gorillaz - new gold ft. tame impala & bootie b...,Gorillaz,8435055.0,282142.0,7399.0,Gorillaz - New Gold ft. Tame Impala & Bootie B...,True,True,6.306347e+07
3,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,on melancholy hill,plastic beach,album,spotify:track:0q6LuUqGLUiCPP1cbdwFs3,0.689,0.739,2.0,-5.810,0.0260,0.000015,0.509000,0.0640,0.578,120.423,233867.0,https://www.youtube.com/watch?v=04mfKJWDSzI,gorillaz - on melancholy hill (official video),Gorillaz,211754952.0,1788577.0,55229.0,Follow Gorillaz online:\nhttp://gorillaz.com \...,True,True,4.346636e+08
4,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,clint eastwood,gorillaz,album,spotify:track:7yMiX7n9SBvadzox8T5jzT,0.663,0.694,10.0,-8.627,0.1710,0.025300,0.000000,0.0698,0.525,167.953,340920.0,https://www.youtube.com/watch?v=1V_xRb0x9aw,gorillaz - clint eastwood (official video),Gorillaz,618480958.0,6197318.0,155930.0,The official music video for Gorillaz - Clint ...,True,True,6.172597e+08

In [140]:
condicion = df["track"].str.contains("\\bfeat\\b", case=True, na=False, regex=True)

In [141]:
df_track = df.loc[condicion]

In [143]:
df_track.head()

,artist,url_spotify,track,album,album_type,uri,danceability,energy,key,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,url_youtube,title,channel,views,likes,comments,description,licensed,official_video,stream
2,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,new gold (feat. tame impala and bootie brown),new gold (feat. tame impala and bootie brown),single,spotify:track:64dLd6rVqDLtkXFYrEUHIU,0.695,0.923,1.0,-3.930,0.0522,0.04250,0.0469,0.116,0.551,108.014,215150.0,https://www.youtube.com/watch?v=qJa-VFwPpYA,gorillaz - new gold ft. tame impala & bootie b...,Gorillaz,8435055.0,282142.0,7399.0,Gorillaz - New Gold ft. Tame Impala & Bootie B...,True,True,63063467.0
6,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,new gold (feat. tame impala and bootie brown) ...,new gold (feat. tame impala and bootie brown) ...,single,spotify:track:2c3KCGq6UojB2c8UAFrRON,0.716,0.897,4.0,-7.185,0.0629,0.01200,0.2620,0.325,0.358,127.030,274142.0,https://www.youtube.com/watch?v=BONNm0F7Tto,"gorillaz - new gold ft. tame impala, bootie br...",Dom Dolla,451996.0,11686.0,241.0,"Gorillaz 'New Gold' ft. Tame Impala, Bootie Br...",False,True,10666154.0
7,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,she's my collar (feat. kali uchis),humanz (deluxe),album,spotify:track:3lIxtCaROdRDuTnNBDm3n2,0.726,0.815,11.0,-5.886,0.0313,0.00799,0.0810,0.112,0.462,140.158,209560.0,https://www.youtube.com/watch?v=f8NwLXYIHS4,gorillaz - she's my collar [hq],SalvaMu√±ox,1010982.0,17675.0,260.0,ùêÅÃ≤ùêéÃ≤ùêçÃ≤ùêîÃ≤ùêíÃ≤:Ã≤ HuÃ≥maÃ≥nÃ≥z [Ã≤Ã†Ã≤ùêÉÃ≤Ã†Ã≤ùêÑÃ≤Ã†Ã≤ùêÖÃ≤Ã†Ã≤ùêàÃ≤Ã†Ã≤ùêçÃ≤Ã†...,False,False,159605929.0
8,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,cracker island (feat. thundercat),cracker island (feat. thundercat),single,spotify:track:2W3ZpQg9i6lE6kmHbcdu9N,0.741,0.913,2.0,-3.340,0.0465,0.00343,0.1030,0.325,0.643,120.012,213750.0,https://www.youtube.com/watch?v=S03T47hapAc,gorillaz - cracker island ft. thundercat (offi...,Gorillaz,24459820.0,739527.0,20296.0,Listen to Cracker Island: https://gorillaz.lnk...,True,True,42671901.0
27,50 Cent,https://open.spotify.com/artist/3q7HBObVc0L8jN...,is this love ('09) (feat. 50 cent),curtain call 2,album,spotify:track:7rK0iM6jwuo1oizdx8suQA,0.853,0.776,8.0,-4.221,0.2610,0.07140,0.0000,0.181,0.659,94.028,212013.0,https://www.youtube.com/watch?v=Zl64MRAqQxk,"eminem, 50 cent - is this love ('09) [visualizer]",EminemVEVO,5289821.0,245935.0,9008.0,"Listen to ""Curtain Call 2"": \nhttps://Eminem.l...",True,True,28529840.0

In [156]:
canciones_por_artista = df_track.groupby("artist")["track"].count().reset_index().sort_values(by = "track", ascending=False)
canciones_por_artista

             artist  track
401      Macklemore     10
61    Bibi und Tina     10
306         Juicy J     10
641   Ty Dolla sign      9
661    Wu-Tang Clan      9
..              ...    ...
329   Kenny Loggins      1
326  Kendrick Lamar      1
324   Kelly Rowland      1
320     Kavita Seth      1
694      √ëengo Flow      1

[695 rows x 2 columns]

In [170]:
df_track.columns

Index(['artist', 'url_spotify', 'track', 'album', 'album_type', 'uri',
       'danceability', 'energy', 'key', 'loudness', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'duration_ms', 'url_youtube', 'title', 'channel', 'views', 'likes',
       'comments', 'description', 'licensed', 'official_video', 'stream'],
      dtype='object')

In [157]:
artistas_colaboraciones_top10 = df_track.groupby("artist")["track"].count().reset_index().sort_values(by = "track", ascending=False)
artistas_colaboraciones_top10.head(10)

            artist  track
401     Macklemore     10
61   Bibi und Tina     10
306        Juicy J     10
641  Ty Dolla sign      9
661   Wu-Tang Clan      9
137      DJ Khaled      9
514        Popcaan      8
660         Wizkid      8
652           Wale      8
416    Mark Ronson      8

In [173]:
artistas_colaboraciones_top10.head(1)

         artist  track
401  Macklemore     10

In [197]:
artista_posicion_1 = artistas_colaboraciones_top10.iloc[0]
artista_posicion_10 = artistas_colaboraciones_top10.iloc[9]

print(f"Artista en la posici√≥n 1: \n",artista_posicion_1)
print("_________________________________")
print(f"Artista en la posici√≥n 10:\n",artista_posicion_10)

Artista en la posici√≥n 1:
 artist    Macklemore
track             10
Name: 401, dtype: object
_________________________________
Artista en la posici√≥n 10:
 artist    Mark Ronson
track               8
Name: 416, dtype: object